version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports:
    - 5432:5432
    volumes:
    - ./.db/data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080

  redis:
    image: 'bitnami/redis:latest'
    environment:
    # ALLOW_EMPTY_PASSWORD is recommended only for development.
    - ALLOW_EMPTY_PASSWORD=yes
    labels:
      kompose.service.type: nodeport
    ports:
    - '6379:6379'
    volumes:
    - 'redis_data:/bitnami/redis'

volumes:
  redis_data:
    driver: local